// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IpcMessageResponseProtobuf.proto

// Protobuf Java Version: 3.25.1
package com.lee.ipc.common.serialization.protobuf.response;

public interface IpcMessageResponseProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IpcMessageResponseProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes data = 1;</code>
   * @return The data.
   */
  com.google.protobuf.ByteString getData();

  /**
   * <code>int32 error_code = 2;</code>
   * @return The errorCode.
   */
  int getErrorCode();

  /**
   * <code>string error_msg = 3;</code>
   * @return The errorMsg.
   */
  java.lang.String getErrorMsg();
  /**
   * <code>string error_msg = 3;</code>
   * @return The bytes for errorMsg.
   */
  com.google.protobuf.ByteString
      getErrorMsgBytes();
}
