// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IpcMessageResponseProtobuf.proto

// Protobuf Java Version: 3.25.1
package com.lee.ipc.common.serialization.protobuf.response;

public final class IpcMessageResponseProtobuf {
  private IpcMessageResponseProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_IpcMessageResponseProto_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_IpcMessageResponseProto_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n IpcMessageResponseProtobuf.proto\"N\n\027Ip" +
      "cMessageResponseProto\022\014\n\004data\030\001 \001(\014\022\022\n\ne" +
      "rror_code\030\002 \001(\005\022\021\n\terror_msg\030\003 \001(\tBR\n2co" +
      "m.lee.ipc.common.serialization.protobuf." +
      "responseB\032IpcMessageResponseProtobufP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_IpcMessageResponseProto_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_IpcMessageResponseProto_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_IpcMessageResponseProto_descriptor,
        new java.lang.String[] { "Data", "ErrorCode", "ErrorMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
