// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IpcMessageRequestProtobuf.proto

// Protobuf Java Version: 3.25.1
package com.lee.ipc.common.serialization.protobuf.request;

/**
 * Protobuf type {@code IpcMessageRequestProto}
 */
public final class IpcMessageRequestProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:IpcMessageRequestProto)
    IpcMessageRequestProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use IpcMessageRequestProto.newBuilder() to construct.
  private IpcMessageRequestProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private IpcMessageRequestProto() {
    serviceUniqueKey_ = "";
    interfaceClass_ = "";
    methodName_ = "";
    parameterTypes_ = emptyList(com.google.protobuf.ByteString.class);
    args_ = emptyList(com.google.protobuf.ByteString.class);
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new IpcMessageRequestProto();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProtobuf.internal_static_IpcMessageRequestProto_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 6:
        return internalGetUserData();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProtobuf.internal_static_IpcMessageRequestProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto.class, com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto.Builder.class);
  }

  public static final int SERVICE_UNIQUE_KEY_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object serviceUniqueKey_ = "";
  /**
   * <code>string service_unique_key = 1;</code>
   * @return The serviceUniqueKey.
   */
  @java.lang.Override
  public java.lang.String getServiceUniqueKey() {
    java.lang.Object ref = serviceUniqueKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      serviceUniqueKey_ = s;
      return s;
    }
  }
  /**
   * <code>string service_unique_key = 1;</code>
   * @return The bytes for serviceUniqueKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getServiceUniqueKeyBytes() {
    java.lang.Object ref = serviceUniqueKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      serviceUniqueKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTERFACE_CLASS_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object interfaceClass_ = "";
  /**
   * <code>string interface_class = 2;</code>
   * @return The interfaceClass.
   */
  @java.lang.Override
  public java.lang.String getInterfaceClass() {
    java.lang.Object ref = interfaceClass_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      interfaceClass_ = s;
      return s;
    }
  }
  /**
   * <code>string interface_class = 2;</code>
   * @return The bytes for interfaceClass.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getInterfaceClassBytes() {
    java.lang.Object ref = interfaceClass_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      interfaceClass_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int METHOD_NAME_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object methodName_ = "";
  /**
   * <code>string method_name = 3;</code>
   * @return The methodName.
   */
  @java.lang.Override
  public java.lang.String getMethodName() {
    java.lang.Object ref = methodName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      methodName_ = s;
      return s;
    }
  }
  /**
   * <code>string method_name = 3;</code>
   * @return The bytes for methodName.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMethodNameBytes() {
    java.lang.Object ref = methodName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      methodName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARAMETER_TYPES_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> parameterTypes_ =
      emptyList(com.google.protobuf.ByteString.class);
  /**
   * <code>repeated bytes parameter_types = 4;</code>
   * @return A list containing the parameterTypes.
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.ByteString>
      getParameterTypesList() {
    return parameterTypes_;
  }
  /**
   * <code>repeated bytes parameter_types = 4;</code>
   * @return The count of parameterTypes.
   */
  public int getParameterTypesCount() {
    return parameterTypes_.size();
  }
  /**
   * <code>repeated bytes parameter_types = 4;</code>
   * @param index The index of the element to return.
   * @return The parameterTypes at the given index.
   */
  public com.google.protobuf.ByteString getParameterTypes(int index) {
    return parameterTypes_.get(index);
  }

  public static final int ARGS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> args_ =
      emptyList(com.google.protobuf.ByteString.class);
  /**
   * <code>repeated bytes args = 5;</code>
   * @return A list containing the args.
   */
  @java.lang.Override
  public java.util.List<com.google.protobuf.ByteString>
      getArgsList() {
    return args_;
  }
  /**
   * <code>repeated bytes args = 5;</code>
   * @return The count of args.
   */
  public int getArgsCount() {
    return args_.size();
  }
  /**
   * <code>repeated bytes args = 5;</code>
   * @param index The index of the element to return.
   * @return The args at the given index.
   */
  public com.google.protobuf.ByteString getArgs(int index) {
    return args_.get(index);
  }

  public static final int USER_DATA_FIELD_NUMBER = 6;
  private static final class UserDataDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, com.google.protobuf.ByteString> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, com.google.protobuf.ByteString>newDefaultInstance(
                com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProtobuf.internal_static_IpcMessageRequestProto_UserDataEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.BYTES,
                com.google.protobuf.ByteString.EMPTY);
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, com.google.protobuf.ByteString> userData_;
  private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
  internalGetUserData() {
    if (userData_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          UserDataDefaultEntryHolder.defaultEntry);
    }
    return userData_;
  }
  public int getUserDataCount() {
    return internalGetUserData().getMap().size();
  }
  /**
   * <code>map&lt;string, bytes&gt; user_data = 6;</code>
   */
  @java.lang.Override
  public boolean containsUserData(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    return internalGetUserData().getMap().containsKey(key);
  }
  /**
   * Use {@link #getUserDataMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getUserData() {
    return getUserDataMap();
  }
  /**
   * <code>map&lt;string, bytes&gt; user_data = 6;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getUserDataMap() {
    return internalGetUserData().getMap();
  }
  /**
   * <code>map&lt;string, bytes&gt; user_data = 6;</code>
   */
  @java.lang.Override
  public /* nullable */
com.google.protobuf.ByteString getUserDataOrDefault(
      java.lang.String key,
      /* nullable */
com.google.protobuf.ByteString defaultValue) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
        internalGetUserData().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, bytes&gt; user_data = 6;</code>
   */
  @java.lang.Override
  public com.google.protobuf.ByteString getUserDataOrThrow(
      java.lang.String key) {
    if (key == null) { throw new NullPointerException("map key"); }
    java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
        internalGetUserData().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceUniqueKey_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, serviceUniqueKey_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(interfaceClass_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, interfaceClass_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(methodName_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, methodName_);
    }
    for (int i = 0; i < parameterTypes_.size(); i++) {
      output.writeBytes(4, parameterTypes_.get(i));
    }
    for (int i = 0; i < args_.size(); i++) {
      output.writeBytes(5, args_.get(i));
    }
    com.google.protobuf.GeneratedMessageV3
      .serializeStringMapTo(
        output,
        internalGetUserData(),
        UserDataDefaultEntryHolder.defaultEntry,
        6);
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(serviceUniqueKey_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, serviceUniqueKey_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(interfaceClass_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, interfaceClass_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(methodName_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, methodName_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < parameterTypes_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(parameterTypes_.get(i));
      }
      size += dataSize;
      size += 1 * getParameterTypesList().size();
    }
    {
      int dataSize = 0;
      for (int i = 0; i < args_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeBytesSizeNoTag(args_.get(i));
      }
      size += dataSize;
      size += 1 * getArgsList().size();
    }
    for (java.util.Map.Entry<java.lang.String, com.google.protobuf.ByteString> entry
         : internalGetUserData().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
      userData__ = UserDataDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .build();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, userData__);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto)) {
      return super.equals(obj);
    }
    com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto other = (com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto) obj;

    if (!getServiceUniqueKey()
        .equals(other.getServiceUniqueKey())) return false;
    if (!getInterfaceClass()
        .equals(other.getInterfaceClass())) return false;
    if (!getMethodName()
        .equals(other.getMethodName())) return false;
    if (!getParameterTypesList()
        .equals(other.getParameterTypesList())) return false;
    if (!getArgsList()
        .equals(other.getArgsList())) return false;
    if (!internalGetUserData().equals(
        other.internalGetUserData())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SERVICE_UNIQUE_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getServiceUniqueKey().hashCode();
    hash = (37 * hash) + INTERFACE_CLASS_FIELD_NUMBER;
    hash = (53 * hash) + getInterfaceClass().hashCode();
    hash = (37 * hash) + METHOD_NAME_FIELD_NUMBER;
    hash = (53 * hash) + getMethodName().hashCode();
    if (getParameterTypesCount() > 0) {
      hash = (37 * hash) + PARAMETER_TYPES_FIELD_NUMBER;
      hash = (53 * hash) + getParameterTypesList().hashCode();
    }
    if (getArgsCount() > 0) {
      hash = (37 * hash) + ARGS_FIELD_NUMBER;
      hash = (53 * hash) + getArgsList().hashCode();
    }
    if (!internalGetUserData().getMap().isEmpty()) {
      hash = (37 * hash) + USER_DATA_FIELD_NUMBER;
      hash = (53 * hash) + internalGetUserData().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code IpcMessageRequestProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:IpcMessageRequestProto)
      com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProtobuf.internal_static_IpcMessageRequestProto_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 6:
          return internalGetUserData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 6:
          return internalGetMutableUserData();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProtobuf.internal_static_IpcMessageRequestProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto.class, com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto.Builder.class);
    }

    // Construct using com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      serviceUniqueKey_ = "";
      interfaceClass_ = "";
      methodName_ = "";
      parameterTypes_ = emptyList(com.google.protobuf.ByteString.class);
      args_ = emptyList(com.google.protobuf.ByteString.class);
      internalGetMutableUserData().clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProtobuf.internal_static_IpcMessageRequestProto_descriptor;
    }

    @java.lang.Override
    public com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto getDefaultInstanceForType() {
      return com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto.getDefaultInstance();
    }

    @java.lang.Override
    public com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto build() {
      com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto buildPartial() {
      com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto result = new com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.serviceUniqueKey_ = serviceUniqueKey_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.interfaceClass_ = interfaceClass_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.methodName_ = methodName_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        parameterTypes_.makeImmutable();
        result.parameterTypes_ = parameterTypes_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        args_.makeImmutable();
        result.args_ = args_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.userData_ = internalGetUserData();
        result.userData_.makeImmutable();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto) {
        return mergeFrom((com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto other) {
      if (other == com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto.getDefaultInstance()) return this;
      if (!other.getServiceUniqueKey().isEmpty()) {
        serviceUniqueKey_ = other.serviceUniqueKey_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getInterfaceClass().isEmpty()) {
        interfaceClass_ = other.interfaceClass_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getMethodName().isEmpty()) {
        methodName_ = other.methodName_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.parameterTypes_.isEmpty()) {
        if (parameterTypes_.isEmpty()) {
          parameterTypes_ = other.parameterTypes_;
          parameterTypes_.makeImmutable();
          bitField0_ |= 0x00000008;
        } else {
          ensureParameterTypesIsMutable();
          parameterTypes_.addAll(other.parameterTypes_);
        }
        onChanged();
      }
      if (!other.args_.isEmpty()) {
        if (args_.isEmpty()) {
          args_ = other.args_;
          args_.makeImmutable();
          bitField0_ |= 0x00000010;
        } else {
          ensureArgsIsMutable();
          args_.addAll(other.args_);
        }
        onChanged();
      }
      internalGetMutableUserData().mergeFrom(
          other.internalGetUserData());
      bitField0_ |= 0x00000020;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              serviceUniqueKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              interfaceClass_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              methodName_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              com.google.protobuf.ByteString v = input.readBytes();
              ensureParameterTypesIsMutable();
              parameterTypes_.add(v);
              break;
            } // case 34
            case 42: {
              com.google.protobuf.ByteString v = input.readBytes();
              ensureArgsIsMutable();
              args_.add(v);
              break;
            } // case 42
            case 50: {
              com.google.protobuf.MapEntry<java.lang.String, com.google.protobuf.ByteString>
              userData__ = input.readMessage(
                  UserDataDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableUserData().getMutableMap().put(
                  userData__.getKey(), userData__.getValue());
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object serviceUniqueKey_ = "";
    /**
     * <code>string service_unique_key = 1;</code>
     * @return The serviceUniqueKey.
     */
    public java.lang.String getServiceUniqueKey() {
      java.lang.Object ref = serviceUniqueKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        serviceUniqueKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string service_unique_key = 1;</code>
     * @return The bytes for serviceUniqueKey.
     */
    public com.google.protobuf.ByteString
        getServiceUniqueKeyBytes() {
      java.lang.Object ref = serviceUniqueKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serviceUniqueKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string service_unique_key = 1;</code>
     * @param value The serviceUniqueKey to set.
     * @return This builder for chaining.
     */
    public Builder setServiceUniqueKey(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      serviceUniqueKey_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string service_unique_key = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearServiceUniqueKey() {
      serviceUniqueKey_ = getDefaultInstance().getServiceUniqueKey();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string service_unique_key = 1;</code>
     * @param value The bytes for serviceUniqueKey to set.
     * @return This builder for chaining.
     */
    public Builder setServiceUniqueKeyBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      serviceUniqueKey_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object interfaceClass_ = "";
    /**
     * <code>string interface_class = 2;</code>
     * @return The interfaceClass.
     */
    public java.lang.String getInterfaceClass() {
      java.lang.Object ref = interfaceClass_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        interfaceClass_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string interface_class = 2;</code>
     * @return The bytes for interfaceClass.
     */
    public com.google.protobuf.ByteString
        getInterfaceClassBytes() {
      java.lang.Object ref = interfaceClass_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        interfaceClass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string interface_class = 2;</code>
     * @param value The interfaceClass to set.
     * @return This builder for chaining.
     */
    public Builder setInterfaceClass(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      interfaceClass_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string interface_class = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearInterfaceClass() {
      interfaceClass_ = getDefaultInstance().getInterfaceClass();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string interface_class = 2;</code>
     * @param value The bytes for interfaceClass to set.
     * @return This builder for chaining.
     */
    public Builder setInterfaceClassBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      interfaceClass_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object methodName_ = "";
    /**
     * <code>string method_name = 3;</code>
     * @return The methodName.
     */
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string method_name = 3;</code>
     * @return The bytes for methodName.
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string method_name = 3;</code>
     * @param value The methodName to set.
     * @return This builder for chaining.
     */
    public Builder setMethodName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      methodName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string method_name = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMethodName() {
      methodName_ = getDefaultInstance().getMethodName();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string method_name = 3;</code>
     * @param value The bytes for methodName to set.
     * @return This builder for chaining.
     */
    public Builder setMethodNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      methodName_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> parameterTypes_ = emptyList(com.google.protobuf.ByteString.class);
    private void ensureParameterTypesIsMutable() {
      if (!parameterTypes_.isModifiable()) {
        parameterTypes_ = makeMutableCopy(parameterTypes_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <code>repeated bytes parameter_types = 4;</code>
     * @return A list containing the parameterTypes.
     */
    public java.util.List<com.google.protobuf.ByteString>
        getParameterTypesList() {
      parameterTypes_.makeImmutable();
      return parameterTypes_;
    }
    /**
     * <code>repeated bytes parameter_types = 4;</code>
     * @return The count of parameterTypes.
     */
    public int getParameterTypesCount() {
      return parameterTypes_.size();
    }
    /**
     * <code>repeated bytes parameter_types = 4;</code>
     * @param index The index of the element to return.
     * @return The parameterTypes at the given index.
     */
    public com.google.protobuf.ByteString getParameterTypes(int index) {
      return parameterTypes_.get(index);
    }
    /**
     * <code>repeated bytes parameter_types = 4;</code>
     * @param index The index to set the value at.
     * @param value The parameterTypes to set.
     * @return This builder for chaining.
     */
    public Builder setParameterTypes(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      ensureParameterTypesIsMutable();
      parameterTypes_.set(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes parameter_types = 4;</code>
     * @param value The parameterTypes to add.
     * @return This builder for chaining.
     */
    public Builder addParameterTypes(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      ensureParameterTypesIsMutable();
      parameterTypes_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes parameter_types = 4;</code>
     * @param values The parameterTypes to add.
     * @return This builder for chaining.
     */
    public Builder addAllParameterTypes(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureParameterTypesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, parameterTypes_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes parameter_types = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearParameterTypes() {
      parameterTypes_ = emptyList(com.google.protobuf.ByteString.class);
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }

    private com.google.protobuf.Internal.ProtobufList<com.google.protobuf.ByteString> args_ = emptyList(com.google.protobuf.ByteString.class);
    private void ensureArgsIsMutable() {
      if (!args_.isModifiable()) {
        args_ = makeMutableCopy(args_);
      }
      bitField0_ |= 0x00000010;
    }
    /**
     * <code>repeated bytes args = 5;</code>
     * @return A list containing the args.
     */
    public java.util.List<com.google.protobuf.ByteString>
        getArgsList() {
      args_.makeImmutable();
      return args_;
    }
    /**
     * <code>repeated bytes args = 5;</code>
     * @return The count of args.
     */
    public int getArgsCount() {
      return args_.size();
    }
    /**
     * <code>repeated bytes args = 5;</code>
     * @param index The index of the element to return.
     * @return The args at the given index.
     */
    public com.google.protobuf.ByteString getArgs(int index) {
      return args_.get(index);
    }
    /**
     * <code>repeated bytes args = 5;</code>
     * @param index The index to set the value at.
     * @param value The args to set.
     * @return This builder for chaining.
     */
    public Builder setArgs(
        int index, com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      ensureArgsIsMutable();
      args_.set(index, value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes args = 5;</code>
     * @param value The args to add.
     * @return This builder for chaining.
     */
    public Builder addArgs(com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      ensureArgsIsMutable();
      args_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes args = 5;</code>
     * @param values The args to add.
     * @return This builder for chaining.
     */
    public Builder addAllArgs(
        java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
      ensureArgsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, args_);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>repeated bytes args = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearArgs() {
      args_ = emptyList(com.google.protobuf.ByteString.class);
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, com.google.protobuf.ByteString> userData_;
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
        internalGetUserData() {
      if (userData_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            UserDataDefaultEntryHolder.defaultEntry);
      }
      return userData_;
    }
    private com.google.protobuf.MapField<java.lang.String, com.google.protobuf.ByteString>
        internalGetMutableUserData() {
      if (userData_ == null) {
        userData_ = com.google.protobuf.MapField.newMapField(
            UserDataDefaultEntryHolder.defaultEntry);
      }
      if (!userData_.isMutable()) {
        userData_ = userData_.copy();
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return userData_;
    }
    public int getUserDataCount() {
      return internalGetUserData().getMap().size();
    }
    /**
     * <code>map&lt;string, bytes&gt; user_data = 6;</code>
     */
    @java.lang.Override
    public boolean containsUserData(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      return internalGetUserData().getMap().containsKey(key);
    }
    /**
     * Use {@link #getUserDataMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getUserData() {
      return getUserDataMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; user_data = 6;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString> getUserDataMap() {
      return internalGetUserData().getMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; user_data = 6;</code>
     */
    @java.lang.Override
    public /* nullable */
com.google.protobuf.ByteString getUserDataOrDefault(
        java.lang.String key,
        /* nullable */
com.google.protobuf.ByteString defaultValue) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetUserData().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, bytes&gt; user_data = 6;</code>
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getUserDataOrThrow(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      java.util.Map<java.lang.String, com.google.protobuf.ByteString> map =
          internalGetUserData().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearUserData() {
      bitField0_ = (bitField0_ & ~0x00000020);
      internalGetMutableUserData().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, bytes&gt; user_data = 6;</code>
     */
    public Builder removeUserData(
        java.lang.String key) {
      if (key == null) { throw new NullPointerException("map key"); }
      internalGetMutableUserData().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, com.google.protobuf.ByteString>
        getMutableUserData() {
      bitField0_ |= 0x00000020;
      return internalGetMutableUserData().getMutableMap();
    }
    /**
     * <code>map&lt;string, bytes&gt; user_data = 6;</code>
     */
    public Builder putUserData(
        java.lang.String key,
        com.google.protobuf.ByteString value) {
      if (key == null) { throw new NullPointerException("map key"); }
      if (value == null) { throw new NullPointerException("map value"); }
      internalGetMutableUserData().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000020;
      return this;
    }
    /**
     * <code>map&lt;string, bytes&gt; user_data = 6;</code>
     */
    public Builder putAllUserData(
        java.util.Map<java.lang.String, com.google.protobuf.ByteString> values) {
      internalGetMutableUserData().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000020;
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:IpcMessageRequestProto)
  }

  // @@protoc_insertion_point(class_scope:IpcMessageRequestProto)
  private static final com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto();
  }

  public static com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IpcMessageRequestProto>
      PARSER = new com.google.protobuf.AbstractParser<IpcMessageRequestProto>() {
    @java.lang.Override
    public IpcMessageRequestProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<IpcMessageRequestProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IpcMessageRequestProto> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.lee.ipc.common.serialization.protobuf.request.IpcMessageRequestProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

