// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IpcMessageRequestProtobuf.proto

// Protobuf Java Version: 3.25.1
package com.lee.ipc.common.serialization.protobuf.request;

public interface IpcMessageRequestProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:IpcMessageRequestProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string service_unique_key = 1;</code>
   * @return The serviceUniqueKey.
   */
  java.lang.String getServiceUniqueKey();
  /**
   * <code>string service_unique_key = 1;</code>
   * @return The bytes for serviceUniqueKey.
   */
  com.google.protobuf.ByteString
      getServiceUniqueKeyBytes();

  /**
   * <code>string interface_class = 2;</code>
   * @return The interfaceClass.
   */
  java.lang.String getInterfaceClass();
  /**
   * <code>string interface_class = 2;</code>
   * @return The bytes for interfaceClass.
   */
  com.google.protobuf.ByteString
      getInterfaceClassBytes();

  /**
   * <code>string method_name = 3;</code>
   * @return The methodName.
   */
  java.lang.String getMethodName();
  /**
   * <code>string method_name = 3;</code>
   * @return The bytes for methodName.
   */
  com.google.protobuf.ByteString
      getMethodNameBytes();

  /**
   * <code>repeated bytes parameter_types = 4;</code>
   * @return A list containing the parameterTypes.
   */
  java.util.List<com.google.protobuf.ByteString> getParameterTypesList();
  /**
   * <code>repeated bytes parameter_types = 4;</code>
   * @return The count of parameterTypes.
   */
  int getParameterTypesCount();
  /**
   * <code>repeated bytes parameter_types = 4;</code>
   * @param index The index of the element to return.
   * @return The parameterTypes at the given index.
   */
  com.google.protobuf.ByteString getParameterTypes(int index);

  /**
   * <code>repeated bytes args = 5;</code>
   * @return A list containing the args.
   */
  java.util.List<com.google.protobuf.ByteString> getArgsList();
  /**
   * <code>repeated bytes args = 5;</code>
   * @return The count of args.
   */
  int getArgsCount();
  /**
   * <code>repeated bytes args = 5;</code>
   * @param index The index of the element to return.
   * @return The args at the given index.
   */
  com.google.protobuf.ByteString getArgs(int index);

  /**
   * <code>map&lt;string, bytes&gt; user_data = 6;</code>
   */
  int getUserDataCount();
  /**
   * <code>map&lt;string, bytes&gt; user_data = 6;</code>
   */
  boolean containsUserData(
      java.lang.String key);
  /**
   * Use {@link #getUserDataMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getUserData();
  /**
   * <code>map&lt;string, bytes&gt; user_data = 6;</code>
   */
  java.util.Map<java.lang.String, com.google.protobuf.ByteString>
  getUserDataMap();
  /**
   * <code>map&lt;string, bytes&gt; user_data = 6;</code>
   */
  /* nullable */
com.google.protobuf.ByteString getUserDataOrDefault(
      java.lang.String key,
      /* nullable */
com.google.protobuf.ByteString defaultValue);
  /**
   * <code>map&lt;string, bytes&gt; user_data = 6;</code>
   */
  com.google.protobuf.ByteString getUserDataOrThrow(
      java.lang.String key);
}
